[Chore] #26 -테스트 코드 작성을 위한 환경 설정
team-B-free/03-GameDuo pull request #27
Opened 2022-07-14 23:06 UTC by StarFace90

<br/>

## 반영 브랜치
Chore/26 -> main

<br/>

## 변경 사항

-  `jest` 테스팅 프레임워크 기반의 환경을 설정하였습니다
-  기존 test 폴더를 보편적으로 사용하는 `__test__` 폴더로 변경하였습니다
- `import(ESM)` 기반으로 테스트 코드를 작성할 수 있도록 하였습니다
-  기존 `exam.test.js` 코드에 예시를 추가 업데이트 하였습니다
<br/>

2022-07-14 23:12 UTC, StarFace90 commented
테스트코드 수정중입니다

2022-07-15 00:11 UTC, KCH6937 approved these changes
확인했습니다!!

2022-07-15 00:13 UTC, whoamixzerone approved these changes
확인했습니다

2022-07-15 00:29 UTC, juhwano requested changes

2022-07-15 00:29 UTC, juhwano commented on src/__test__/exam/testModules.js
> +/**
test파일은 카멜케이스로 작성해야하나요?

2022-07-15 00:29 UTC, juhwano commented on src/__test__/exam/exam.test.js
> +/**
저희 프로젝트 통일성때문에 __test__폴더보다 test 폴더로 작성해도 작동에 문제 없다면 test로 통일하는 게 어떠신가요??

2022-07-15 00:36 UTC, StarFace90 commented on src/__test__/exam/testModules.js
> +/**
파일이름을 카멜케이스로 작성했네요 😢 수정하겠습니다

2022-07-15 00:37 UTC, StarFace90 commented on src/__test__/exam/exam.test.js
> +/**
위와 동일한 내용이며 작동에 문제가 없음으로 수정하겠습니다!

2022-07-15 00:46 UTC, merged